### ISSUE TITLE
Problem in thread maybe !

### ISSUE THREAD

**Issue by AIC2019** [SharifAIChallenge/AIC19-Client-Cpp#1]
slm, Aya thread ha be dorosti baham kar mikonan? tu code man thread ha hamzaman yek seri variable ro taghir midan!!!!

------------

age tu ye phase az time limit kharej beshim, aya system be karesh edame mide? (manzuram thread has) ya na kolan return mishe ta phase badi?

**Comment by RuhollahSeka** [comment]
در صورتی که زمان اجرای تردی از مدت زمان گفته شده بگذرد، سرور پیام جدید را فرستاده و در کلاینت ترد جدید شروع به کار می‌کند ولی ترد قبلی کلاینت قطع نمی‌شود. در صورت طول کشیدن بیش از اندازه اجرای یک ترد، مدیریت منابع مشترک با خودتان است
