### ISSUE TITLE
Segmention fault??

### ISSUE THREAD

**Issue by kingk13** [SharifAIChallenge/AIC19-Client-Cpp#12]
موقع اضافه کردن یه عضو به وکتور خطای Segmentation fault(core dumped) داده میشه:

AI.h:

`#ifndef AIC19_CLIENT_CPP_AI_H
#define AIC19_CLIENT_CPP_AI_H

//#include <Model/World.h>
#include <Model/Interface/World.h>

class AI {
public:
    void preProcess(World* world);

    void pick(World* world);

    void move(World* world);

    void action(World* world);

private:
    int pickTurn = 0;

    std::vector<Hero *> AlyHeroes;
    std::vector<Hero *> OppHeroes;

};

#endif // AIC19_CLIENT_CPP_AI_H
`

AI.cpp:

`#include "AI.h"

void AI::preProcess(World *world) {
    std::cout << "[#] preProcess\n";
    std::cout << "[$] Pick Phase:\n";
}

void AI::pick(World *world) {
    std::cout << "[$] Pick #" << pickTurn+1 << ":\n";
    switch (pickTurn)
    {
        case 0:
            world->pickHero(HeroName::BLASTER);
            std::cout << "[+]Alley Team: BLASTER\n";
            break;
        case 1:
            world->pickHero(HeroName::SENTRY);
            std::cout << "[+]Alley Team: SENTRY\n";
            break;
        case 2:
            world->pickHero(HeroName::HEALER);
            std::cout << "[+]Alley Team: HEALER\n";
            break;
        case 3:
            world->pickHero(HeroName::GUARDIAN);
            std::cout << "[+]Alley Team: GUARDIAN\n";
            break;
        default:
            break;
    }
    OppHeroes.push_back(world->getMyHeroes().back());
    OppHeroes.push_back(world->getOppHeroes().back());
    std::cout << "[-]Opponent Team: " << OppHeroes.back()->getName() << std::endl;
    pickTurn++;
}

void AI::move(World *world) {
    std::cout << "[^]Move Phase:\n";
}

void AI::action(World *world) {
    std::cout << "[*]Action Phase:\n";
}`

Output:

`[Info]      AI Challenge 2019 C++ Client v1.0.0
[Info]      Trying to connect #1
[Info]      Connected
[Info]      Starting init Message parse...
[#] preProcess
[$] Pick Phase:
[Info]      Received Pick message from server
[Info]      Received update_game server
[$] Pick #1:
[+]Alley Team: BLASTER
Segmentation fault (core dumped)
`

**Comment by onajafi** [comment]
سلام،
بعد از صدا زدن 
`world->pickHero()`
اطلاعات
world
در همان لحظه آپدیت نمیشود و در نوبت بعد آپدیت میشود
برای همین است که 
world->getMyHeroes()
خالی و خواندن مقدار از آن بی معنی است.
