### ISSUE TITLE
جمع کردن همه چی تو یه ریپازیتوری

### ISSUE THREAD

**Issue by amiralisalimi** [SharifAIChallenge/AIC19-Client-Cpp#13]
سلام
خسته نباشید
 اگه ی لطفی کنید همه چیزو تو یک ریپو بریزید هم آپدیت کردن راحت تره هم اساسا بهتره! :)

**Comment by hamidreza004** [comment]
> سلام
> خسته نباشید
> اگه ی لطفی کنید همه چیزو تو یک ریپو بریزید هم آپدیت کردن راحت تره هم اساسا بهتره! :)

اینجوری کدوم کلاینت رو بریزیم تو ریپازیتوری خب؟ 
هر کی متناسب  خودش باید فایل‌ها رو دریافت کنه.
