### ISSUE TITLE
مشکل تابع isInVision

### ISSUE THREAD

**Issue by ImaniAm** [SharifAIChallenge/AIC19-Client-Cpp#15]
سلام. خسته نباشید
بنده یه کدی زدم که بعد از اجرای سرور وقتی کلاینتمو اجرا می کنم در جا سگمنتیشن فالت می خوره. رفتم و AI.cpp را بررسی کردم و به این نتیجه رسیدم که تابع isInVision() به ازای یه جفتی از سل ها خوب کار نمی کنه و بعد از اجراش ران تایم میشه. ممنون میشم اگر پیگیری کنید چون بنده کاملا بر اساس سینتکس های توی مستند کد زدم. توی کدم توی تابع پری پراسس توی خط ۲۳ تا ۲۷ به ازای i = 80, j = 591 کدم ران تایم میشه. چک کردم مشکل از تابع getcell هم نیستش. ممنون میشم اگر پیگیری بفرمایید
[myclient1.zip](https://github.com/SharifAIChallenge/AIC19-Client-Cpp/files/2852987/myclient1.zip)

**Comment by onajafi** [comment]
سلام،
ظاهرا اشکال از طرف کلاس های نوشته شده هستش.
بزودی آپدیت جدید می‌دهیم.

ممنون!

**Comment by onajafi** [comment]
می‌توانید ورژن ۱.۱.۱ را استفاده کنید

**Comment by ImaniAm** [comment]
ممنون از پیگیریتون. لطف کردید :)
