### ISSUE TITLE
W->getMap().getObjectiveZone() return Null Cells

### ISSUE THREAD

**Issue by AIC2019** [SharifAIChallenge/AIC19-Client-Cpp#16]
slm

W->getMap().getObjectiveZone() Cell haye null return mikone!!!
(client, server, map ha ham updatan)
![screen shot 2019-02-12 at 1 22 22 pm](https://user-images.githubusercontent.com/47473632/52626898-6c318680-2ec9-11e9-9e03-4e83f1378d76.png)

**Comment by onajafi** [comment]
سلام،
آیا مشکل شما حل شد؟

**Comment by AIC2019** [comment]
bale, moshkel az update nabudan clientam bud, SRY :(
