### ISSUE TITLE
حرکت نکردن هیرو ها

### ISSUE THREAD

**Issue by MohsenDehghankar** [SharifAIChallenge/AIC19-Client-Cpp#17]
هیرو ها حتی توی کد پیش فرض زده شده در کلاینت سی پلاس پلاس حرکت نمی کنند.
با سی لاین اجرا می کنم و آخرین نسخه سرور رو هم دارم

**Comment by onajafi** [comment]
سلام،

کد پیش‌فرض به این صورت است که هیروها بعد از هر ۲۰ نوبت کامل به طور تصادفی نقطه‌ای جدید را در نقشه انتخاب می‌کنند و در ۲۰ نوبت بعدی سعی می‌کنند که به آن نقطه هدف، خود را برسانند و در آنجا مستقر شوند.

برای حرکت پی در پی هیروها می‌توانید خط۷۶ از فایل
`AI.cpp`
را بصورت زیر تغییر دهید:
`targetRefreshPeriod = 3 * 6;`

**Comment by MohsenDehghankar** [comment]
نه باز هم حرکتی نمی کنن. من حتی کد تابع حرکت رو خوم نوشتم ولی حرکتی نمی کنن هیرو ها. کد مشابه رو در کلاینت جاوا زدم اونجا مشکلی نداشت و حرکت انجام می شد.

**Comment by onajafi** [comment]
لطفا فایل لاگ را ارسال کنید تا خروجی‌های ارسال شده از طرف کلاینت، بررسی شوند

**Comment by MohsenDehghankar** [comment]
[server_view.log](https://github.com/SharifAIChallenge/AIC19-Client-Cpp/files/2859156/server_view.log)
[graphic.log](https://github.com/SharifAIChallenge/AIC19-Client-Cpp/files/2859157/graphic.log)

**Comment by onajafi** [comment]
ببخشید
منظورم از فایل لاگ فایل
`client.log`
هست که در کنار جایی که برنامه اجرا می‌شود ساخته می‌شود

اگر با 
CLion
کلاینت را اجرا می‌کنید باید در آدرسی ذخیره شود که بالای پنجره
`run`
نوشته شده.
