### ISSUE TITLE
ارور

### ISSUE THREAD

**Issue by AliRn76** [SharifAIChallenge/AIC19-Client-Cpp#18]
![screenshot 690](https://user-images.githubusercontent.com/40032682/52654688-c6e9d300-2f07-11e9-9394-e015ea53660d.png)
سلام ، آقا من مشکل رو چجوری حل کنم ، با 
cygwin
 کامپایل شده

**Comment by AliRn76** [comment]
قبلش با 
minGW
 کامپایل میکردم این اررور زیر رو میداد
`mutex in namespace std does not name a type`

**Comment by onajafi** [comment]
با سلام،
ظاهرا مشکل از تابع کمکی
`make_unique`
هست

لطفا آخرین [کامیت](https://github.com/SharifAIChallenge/AIC19-Client-Cpp/commit/42b8b3c264541c4eb569165c019fc41b01d9c6a8) روی شاخه 
`AIC_2019`
را تست کنید و نتیجه آن را در اینجا ارسال کنید.
در کامیت آخر، وابستگی کد از این تابع کمکی را حذف کردم.

**Comment by AliRn76** [comment]
![screenshot 692](https://user-images.githubusercontent.com/40032682/52669461-62406f80-2f2b-11e9-9122-aa70768299dd.png)
مشکل از کامپایلر نیست؟

**Comment by AliRn76** [comment]
![screenshot 693](https://user-images.githubusercontent.com/40032682/52670325-7edda700-2f2d-11e9-872e-a9f535d22209.png)

**Comment by onajafi** [comment]
فایل
`cmake`
رو عوض کردین؟

ظاهرا داره فایل‌های تست کتابخانه 
`JsonCpp`
رو هم کامپایل می‌کنه

**Comment by onajafi** [comment]
ظاهرا مشکل از تنظیمات
toolchain
می‌باشد.

برای بررسی آن در 
CLion
به بخش زیر بروید:
`File-> settings-> ToolChain`
و بررسی کنید که آیا
enviroment
شما به
`cygwin64`
تنظیم شده است یا خیر
اگر 
`MinGW`
باشد باید آن را عوض کنید.

برای نصب 
`cygwin64`
به لینک زیر سر بزنید:
https://www.jetbrains.com/help/clion/quick-tutorial-on-configuring-clion-on-windows.html
