### ISSUE TITLE
عدم حرکت بعضی هیرو ها

### ISSUE THREAD

**Issue by xaoirse** [SharifAIChallenge/AIC19-Client-Cpp#19]
تو این لاگ که گذاشتم تو ترن 4 و 5 فاز حرکت 4 و 5 کار نمیکنه یا فقط دوتا از هیرو ها رو حرکت میده و هر بارم برنامه کلاینت اجرا میشه همین اتفاق به صورت رندوم میفته حتی موقع اجرای کدهای پیشفرض که قرار داده بودینم این اتفاق میفته
کلاینت و سرور آخرین نسخه هستند
[graphic.log](https://github.com/SharifAIChallenge/AIC19-Client-Cpp/files/2858155/graphic.log)
[client.log](https://github.com/SharifAIChallenge/AIC19-Client-Cpp/files/2858156/client.log)

**Comment by RuhollahSeka** [comment]
با توجه به لاگ های داده شده، در چند نوبت اول دلیل توقف هیروها، تمام شدن ap است
بعد از چند نوبت اول دلیل اینکه کلا هیروها حرکت نمی‏‌کنند این است که دو هیرو به مقصد خود رسیده و دیگر دستور حرکت برای آنان نمی‌آید و دستور حرکت دو هیرو دیگر به سمت خانه همان دو هیرو اول است و در نتیجه قابل قبول نیست پس مشکلی در سرور یا کلاینت وجود ندارد
