### ISSUE TITLE
نحوه نوشتن اسم توابع در سی پلاس پلاس

### ISSUE THREAD

**Issue by SMSadegh19** [SharifAIChallenge/AIC19-Client-Cpp#2]
توی داک در مورد اسم توابع در جاوا و پایتون گفته شده، ولی برای سی نگفتن.

**Comment by onajafi** [comment]
سلام،
اسامی تمامی توابع و کلمات تعریف شده (اینام ها)مطابق [داک](https://github.com/SharifAIChallenge/AIC19-Doc/releases)(از صفحه ۱۵ به بعد) تعریف شده است.

نکته قابل توجه این است که برخی از توابع که خروجی آرایه دارند، خروجی آنها بصورت یک وکتور از اشاره گرها می‌باشد.
برای مثال در داک نوشته شده: 
Hero[] getMyHeroes()
اما خروجی این تابع در کلاینت سی پلاس پلاس بصورت زیر است:
std::vector<Hero *>
و می‌توان به روش زیر از آن استفاده کرد:

```
for(Hero* _hero : world->getMyHeroes()){
    std::cout << _hero->getId() << std::endl;
}
```
