### ISSUE TITLE
world->getOppHeroes()

### ISSUE THREAD

**Issue by AIC2019** [SharifAIChallenge/AIC19-Client-Cpp#22]
slm, mage vase opp haii ke tu did nistan nabayad row va col -1 bashe?

![image](https://user-images.githubusercontent.com/47473632/52779866-412c6b80-305e-11e9-82d9-58dc1c0a0358.png)

**Comment by onajafi** [comment]
سلام،
بله درست می‌فرمایید
در آپدیت بعدی این اشکال را برطرف خواهیم کرد.

در واقع هنگامی که قهرمان حریف دیده نمی‌شود باید 
NULL_CELL
برگردانده شود.

**Comment by onajafi** [comment]
لطفا ریلیز ۱.۱.۲ را استفاده کنید
در صورت بطرف نشدن مشکل این بخش را باز کنید
