### ISSUE TITLE
create array !!

### ISSUE THREAD

**Issue by AIC2019** [SharifAIChallenge/AIC19-Client-Cpp#23]
chera vaghti mikham ye array (farz konid ba size kheyli ziad) define konam tuye function error mide (Exception: EXC_BAD_ACCESS (code=1, address=0x70000fb06c48))
amma vaghti hamun ro global tarif mikonam moredi nadare? aya limiti ruye thread hast?
mamnun misham tozih bedid

**Comment by onajafi** [comment]
سلام،
محدودیتی روی حجم استفاده از حافظه قرار داده نشده.

نکته‌ای که باید به آن توجه داشت این هست که این توابع هر کدام بر روی یک ترد اجرا می‌شوند و هیچ کدام از تردها بعد از اتمام زمان اختصاص داده شده به آنها بسته نمی‌شود و تا هنگامی که تابع نیاز به اجرا داشته باشد به کار خود ادامه می‌دهد.

به همین دلیل امکان دارد که تابع شما همزمان در چند ترد در حال اجرا باشد و اگر هر کدام از توابع میزان حافظه‌ی اختصاصی زیادی برای خود مصرف کنند امکان این هست که حافظه اختصاصی برنامه تمام شود و با ارور کمبود حافظه مواجح شوید.

اگر حافظه را بصورت گلوبال یا استاتیک تعریف کنید با این مشکل مواجح نخواهید شد.

**Comment by onajafi** [comment]
این را هم اضافه کنم که **هنگام سابمیت** کد میزان حافظه رم اختصاص داده شده به هر کلاینت برابر
`1G`
می‌باشد.

**Comment by AIC2019** [comment]
in tabeii ke migam serfan faghat to preprocess farakhuni mishe pas un farzi ke migid fekr nakonam pish biad !

**Comment by onajafi** [comment]
در اینصورت بله درست می‌فرمایید.

تنها دلیلی که می‌مونه محدود بودن حافظه
stack
در برنامه هست 
چرا که این حافظه به متغیر های درون تابع اختصاص داده می‌شود
اما درصورتی که متغیرهای خود را بصورت
Global یا Static
تعریف کنید، متغیرها در حافظه 
Static
ذخیره می‌شوند.

راه دیگری که می‌توانید با آن متغیر های خود را درون تابع (مختص هر بار اجرای تابع) تعریف کنید استفاده از 
`new`
است
برای مثال عبارت زیر(که درون تابع اجرا می‌شود):
`int* my_arr = new int[10000];`
حافظه‌ی
heap
را اشغال می‌کند و نیازی نیست بخش عمده‌ای از حافظه
static
را اشغال کند
از طرفی حافظه
heap
محدودیت کمتری دارد و می‌توانید حجم بیشتری از آن را اشغال کنید.

برای اطلاعات بیشتر به لینک زیر سر بزنید :
https://craftofcoding.wordpress.com/2015/12/07/memory-in-c-the-stack-the-heap-and-static/
