### ISSUE TITLE
سگمنتیشن فالت کد کلاینت

### ISSUE THREAD

**Issue by ImaniAm** [SharifAIChallenge/AIC19-Client-Cpp#25]
سلام. بنده یه بازی اجرا کردم که توش کد خودم با کد پیش فرض که در اختیارمون قرار داده شده بازی می کرد و کد پیش فرض سگمنتیشن فالت خورد. بنده از آخرین نسخه کلاینت و سرور استفاده کردم. ممنون میشم اگر پیگیری بفرمایید. این هم کلاینت بنده هستش:
[myclient1.zip](https://github.com/SharifAIChallenge/AIC19-Client-Cpp/files/2868690/myclient1.zip)

**Comment by onajafi** [comment]
سلام،

کد شما بدون هیچ مشکلی برروی سیستم من(اوبونتو۱۸.۴) قابل اجرا هست.
ورژن سرور مورد استفاده:
`v1.1.3`

امکان این هست که در صورت 
terminate
کردن در وسط تست‌های قبلی، تعدادی ترد همچنان باز باشد که باعث اختلال در تست‌های بعدی شما شود.
 در اینصورت باید سیستم را ری استارت کرد.

اگر مشکل شما حل نشد لطفا فایل
`client.log`
واقع در **محل اجرای کلاینت** را ارسال کنید.
برای پیدا کردن آدرس محل اجرای کلاینت در 
CLion
 به آدرسی که در بالای پنجره 
run
است مراجعه کنید.

**Comment by ImaniAm** [comment]
سلام. اقا کد بنده روی سیستم خودمم درست کار می کنه. بنده گفتم کد پیش فرض کلاینت را گذاشتم جلوی کد خودم تا با هم بازی کنن. یعنی سرور را اجرا کردم بعدش اول کلاینت خودم و بعدش کلاینت پیش فرض را گذاشتم که با هم بازی کنند. بعدش کلاینت پیش فرض سگمنتیشن فالت خورد. نه کلاینت بنده

**Comment by onajafi** [comment]
شما درست فرمودین
مشکل از طرف یکی از توابع کلاس
world
بود

این مشکل در ریلز ۱.۱.۴ کلاینت برطرف شده است.

بابت مطرح کردن این مشکل از شما سپاس‌گزارم.

**Comment by ImaniAm** [comment]
خواهش می کنم. ممنون از پیگیریتون.
