### ISSUE TITLE
مشکل تابع getRemRespawnTim

### ISSUE THREAD

**Issue by ImaniAm** [SharifAIChallenge/AIC19-Client-Cpp#27]
سلام. فکر می کنم طبق تعریف این تابع باید تعداد نوبت هایی که مانده تا قهرمان زنده بشه را بده دیگه. یعنی اینکه اگر قهرمانمون زنده باشه این تابع مقدارش برابر صفر هستش. همچنین اگر مقدار این تابع برابر یک باشه و ما توی نوبت ایکس باشیم یعنی اینکه قهرمانمون توی نوبت ایکس به علاوه یک زنده میشه و ما می توانیم حرکتش بدیم. اگر اشتباه می کنم بفرمایید.
الان توی کدی که بنده زدم یه جایی برای اینکه چک کنم قهرمانم زنده هستش یا نه اومدم از این تابع استفاده کردم و چک کردم مقدارش برابر با صفر هست یا نه. ولی هیچ وقت قهرمانی از من زنده در نظر گرفته نمیشد. چک کردم و دیدم که به اضای قهرمانان زنده تابع مورد نظر مقدار پنج را بر می گرداند. ممنون میشم اگر پیگیری بفرمایید.
[myclient1.zip](https://github.com/SharifAIChallenge/AIC19-Client-Cpp/files/2872139/myclient1.zip)

**Comment by RuhollahSeka** [comment]
مشکل از سرور بود و در ریلیز جدید برطرف شده است

**Comment by ImaniAm** [comment]
سلام. ممنونم از پیگیریتون
