### ISSUE TITLE
(v1.1.4) -> ObjectiveZone.back() became NULL_CELL after calling isInVision()

### ISSUE THREAD

**Issue by SamMHD** [SharifAIChallenge/AIC19-Client-Cpp#30]
سلام!!
بعد از صدا کردن 
isInVision
 روی تمام سل های آبجکتیو، خانه آخر آبجکتیو به 
NULL_CELL 
تبدیل میشود
Client Version: v1.1.4
Map: Normal2
Cell (18, 18) became NULL_CELL
پ. ن. در صورت ذخیره سطر و ستون ها به صورت زوج عدد صحیح نیز مشکل باقی میماند

<img width="691" alt="screen shot 2019-02-18 at 12 02 38 pm" src="https://user-images.githubusercontent.com/46444723/52937734-2ff0a100-3375-11e9-9902-48e4b6783e8d.png">

در صورت کامنت کردن خط ۵۰ و ۵۱ کد بدون هیچ مشکلی اجرا میشود

**Comment by onajafi** [comment]
سلام!!
مشکل در ریلیز [۱.۱.۶](https://github.com/SharifAIChallenge/AIC19-Client-Cpp/releases/tag/v1.1.6) برطرف شد.
ممنون از اینکه گزارش کردین!
