### ISSUE TITLE
Do the attack

### ISSUE THREAD

**Issue by Alishrf** [SharifAIChallenge/AIC19-Client-Cpp#33]
if(target_attack_cell == Cell::NULL_CELL) {
                world->castAbility(*my_hero, AbilityName::BLASTER_ATTACK,target_attack_cell);
            }

//fekr konam shart if bayad injori bashe :

if(target_attack_cell != Cell::NULL_CELL) {
                world->castAbility(*my_hero, AbilityName::BLASTER_ATTACK,target_attack_cell);
            }

**Comment by onajafi** [comment]
سلام،
بله، شما درست می‌فرمایید :)))
ممنون از اینکه پیداش کردین!
