### ISSUE TITLE
problem to C++ code

### ISSUE THREAD

**Issue by omidima** [SharifAIChallenge/AIC19-Client-Cpp#35]
با سلام
کد C++ کلاینت
به هیچ عنوان کامپایر نمیشه و تقریبا پنج فایل آن مشکل داره لطفا برسی نمایید

**Comment by onajafi** [comment]
سلام،
لطفا یه اسکرین شات از ارور رو اینجا بفرستین
و نیز بفرمایید که در چه محیطی (ویندوز، لینوکس و...) کد را کامپایل کردین.

پ. ن. اگر از ویندوز استفاده میکنید شما را به این ایشیو ارجاع می‌دم:
issue #18

**Comment by AIC2019** [comment]
slm, bande ham hamin moshkel ro daram, codie ke ru system khodam (mac OS) compile mishe va run migiram vaghti up mikonam failed mishe!.
![image](https://user-images.githubusercontent.com/47473632/53068631-6271d980-34ee-11e9-97a7-d975b34c00f9.png)

yadame parsal ham hamin moshkel bud ke client update shod va fix shod

https://github.com/SharifAIChallenge/AIC18-Client-Cpp/issues/13
