### ISSUE TITLE
compile error on site

### ISSUE THREAD

**Issue by AIC2019** [SharifAIChallenge/AIC19-Client-Cpp#38]
slm, codi ke ru system khodam (mac OS) compile mishe va run migiram vaghti up mikonam failed mishe!.
![image](https://user-images.githubusercontent.com/47473632/53068631-6271d980-34ee-11e9-97a7-d975b34c00f9.png)

yadame parsal ham hamin moshkel bud ke client update shod va fix shod

https://github.com/SharifAIChallenge/AIC18-Client-Cpp/issues/13

**Comment by onajafi** [comment]
سلام،
ظاهرا این پیام در هنگام وجود خطای کامپایل نمایش داده می شود
و مشکل از کد درون 
AI.cpp
است
:)
