### ISSUE TITLE
کم هیل کردن

### ISSUE THREAD

**Issue by ImaniAm** [SharifAIChallenge/AIC19-Client-Cpp#39]
سلام. بنده یه بازی کردم که توش کلاینت خودم با خودم بازی می کرد. بعدش دیدم یکی از تیما هیل می کنه بازیکناشو و جونشونم زیاد میشه ولی اون مقداری که جان بازیکن روی نمایشگر تغییر می کنه واضحه که کمتر از ۳۰ هستش و به خاطر همینم بازیکنا  زود می میرند. راستش نمی دونم مشکل از سرور یا کلاینت یا نمایشگر هستش ولی ممنون میشم اگر پیگیری بفرمایید. این هم کلاینت بنده و فایل لاگ بازی هستش. از نسخه اخر سرور و کلاینت هم استفاده کردم.
[1.zip](https://github.com/SharifAIChallenge/AIC19-Client-Cpp/files/2889443/1.zip)

**Comment by onajafi** [comment]
سلام،
با توجه به لاگ فرستاده شده
در بعضی از مراحل چند عمل 
HEAL
و چند عمل
ATTACK
با هم انجام شده است.
و اگر از هر دونوع عمل بر روی یک قهرمان اعمال شود میتواند میزان جان اون رو کمتر از میزان
HEAL
تغییر دهد

**Comment by ImaniAm** [comment]
بسیار هم عالی. ممنون از پیگیریتون.
