### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005) (solved)

### ISSUE THREAD

**Issue by xaoirse** [SharifAIChallenge/AIC19-Client-Cpp#4]
تقریبا تو حرکتهای اول کلاینت  خارج میشه
Process finished with exit code -1073741819 (0xC0000005)

[client.log](https://github.com/SharifAIChallenge/AIC19-Client-Cpp/files/2849023/client.log)

[graphic.log](https://github.com/SharifAIChallenge/AIC19-Client-Cpp/files/2849025/graphic.log)

**Comment by onajafi** [comment]
سلام،
برای تحلیل دقیق‌تر مشکل شما نیاز به اطلاعات بیشتری داریم.
لطفا خط ۱۰۵ واقع در فایل زیر را از حالت کامنت خارج کنید:
/src/Network/Network.cpp
و دوباره فایل
client.log
را ارسال کنید.

**Comment by xaoirse** [comment]
[client.log](https://github.com/SharifAIChallenge/AIC19-Client-Cpp/files/2849205/client.log)
 
نمیدونم چرا ولی وقتی یک دستور پرینت مینویسم که هر فاز و ترن و آی دی هیرو رو نشون بده برنامه اجرا میشه تا 
آخر ولی وقتی باز پرینت هارو کامنت میکنم دومین باری که میخاد تابع حرکت رو اجرا کنه خارج میشه

خب این مشکل تو ورژن 1.0.1 سرور نیست

**Comment by onajafi** [comment]
ظاهرا مشکل از سمت سرور بود
در صورت بروز مجدد اشکال این موضوع را دوباره باز کنید
