### ISSUE TITLE
Timeout on actions

### ISSUE THREAD

**Issue by Mohre** [SharifAIChallenge/AIC19-Client-Cpp#42]
من تمامی محتوای موجود در توابع حرکت و عمل کد نمونه‌ی داده شده را پاک کردم.
با این حال زمان مورد استفاده برای اجرای توابع خالی حدود ۹۰۰ میلی ثانیه است که بیشتر از حد معمول است
چکار باید بکنم که دستورات در مدت داده شده قابل اجرا باشند؟

**Comment by onajafi** [comment]
سلام،
درست می‌فرمایید، این میزان زمان برای دریافت داده‌ها از طرف سرور و پردازش اولیه آنها است.
اما این میزان زمان در سرور کمتر است.
برای اینکه شما در کامپیوترتان به مشکل کمبود زمان برنخورید می‌توانید به صورت زیر سرور را ران کنید
`java -jar server.jar --extra=900`
در مثال بالا ۹۰۰ میلی ثانیه به فرصت اجرای هر تابع از کلاینت اضافه خواهد شد.
