### ISSUE TITLE
getOffensiveAbilities() return empty vector

### ISSUE THREAD

**Issue by mastermobin** [SharifAIChallenge/AIC19-Client-Cpp#44]
In Tabe Roye Enemy Ha Hamishe Khalie Dar Hali Ke Dar Client Java In Moshkel Vojod Nadare

**Comment by onajafi** [comment]
سلام،
این باگ در یکی از کلاس‌های ساخته شده بود که در ریلیز [۱.۱.۹](https://github.com/SharifAIChallenge/AIC19-Client-Cpp/releases/tag/v1.1.9) برطرف شده است.
بابت گزارش این باگ ممنونم.
