### ISSUE TITLE
Unkown Bug!

### ISSUE THREAD

**Issue by FakeAlisad** [SharifAIChallenge/AIC19-Client-Cpp#5]
`Map gameMap = world->getMap();`
`vector<Cell*> objectiveZones;`
`objectiveZones = gameMap.getObjectiveZone();`
`if (!objectiveZones[0]->isInObjectiveZone())`
`	std::cout << "ExCuz Mi WhatTheFuZZ?" << std::endl;`

alan in varede if mishe va **ExCuz Mi WhatTheFuZZ** ro chap mikone vali nabayad in ettefagh biofte

**Comment by onajafi** [comment]
سلام
لطفا فایل لاگ برنامه را ارسال کنید و نیز این خط را قبل از شرط اضافه کنید:
`std::cout << "Vector size is: " << objectiveZones.size() << std::endl;`

**Comment by FakeAlisad** [comment]
**Vector size is: 96** va inke kodum log ro bedam (server_view ya graphic)?

**Comment by onajafi** [comment]
client.log
را ارسال کنید

**Comment by FakeAlisad** [comment]
[client.log](https://paste.ubuntu.com/p/7JxwVGgtpq/)

**Comment by onajafi** [comment]
شما از کلاینت [جدید](https://github.com/SharifAIChallenge/AIC19-Client-Cpp/releases/tag/v1.1.1) دارید استفاده می‌کنید؟ 

من کد شما را امتحان که می‌کنم به این خروجی بر نمی‌خورم.
اگر با کلاینت جدید محددا با این مشکل مواجه شدین خط ۱۰۵ در فایل زیر را از حالت کامنت خارج کنید و دوباره فایل کلاینت خروجی را ارسال کنید:
/src/Network/Network.cpp

ممنون!
