### ISSUE TITLE
Known Bug (Healer)!

### ISSUE THREAD

**Issue by FakeAlisad** [SharifAIChallenge/AIC19-Client-Cpp#7]
`world->pickHero(HeroName::HEALER)`
in dastoor `HeroName::GUARDIAN` ro pick mikone va na HEALER
[moshkele taghriban moshabeh](https://github.com/SharifAIChallenge/AIC19-Client-Cpp/issues/6)

**Comment by onajafi** [comment]
سلام
شما را به پاسخ
issue #6 
ارجاع می‌دهم
لطفا همان کار را با
`HeroName::HEALER`
انجام دهیدو
