### ISSUE TITLE
مشکل اد به وکتور

### ISSUE THREAD

**Issue by ImaniAm** [SharifAIChallenge/AIC19-Client-Cpp#8]
سلام. بنده توی کدم به یه کامپایل اروری برخوردم که خیلی روش وقت گذاشتم و بالاخره فهمیدم که دلیلش ربطی به کد من نداره. بلکه دلیلش عدم قابلیت پوشبک برای یه وکتور از جنس هیرو هستش. یعنی من یه وکتور از جنس هیرو داشته باشم نمی تونم تابع پوش بک را براش صدا کنم وگرنه کامپایل ارور می خورم. ممنون میشم اگر پیگیری بفرمایید. چون اگر نتونیم از وکتور استفاده کنیم کدمون خیلی کثیف تر میشه 
[myclient1.zip](https://github.com/SharifAIChallenge/AIC19-Client-Cpp/files/2849413/myclient1.zip)

**Comment by DanialErfanian** [comment]
سلام
ببین من دقیق نفهمیدم مشکل چیه ولی شهودم اینه که یه حالت کانستنت طوری داره هیرو.
و اگه به جای وکتور از هیرو ها, ی وکتور از پویتر به هیرو بگیری حله مشکل
